"""Code explanation skill.

Explains code functionality in natural language.

Capabilities:
- Explain function/method behavior
- Document complex algorithms
- Describe code flow
- Identify potential issues
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from skills.core.base_skill import BaseSkill, SkillContext, SkillResult, SkillCategory, SkillStatus


@dataclass
class ExplanationOutput:
    """Output from code explanation."""
    summary: str
    detailed_explanation: str
    complexity: str  # low, medium, high
    potential_issues: List[str] = field(default_factory=list)
    suggestions: List[str] = field(default_factory=list)


class CodeExplanationSkill(BaseSkill):
    """Explain code functionality in natural language.
    
    Uses LLM to analyze code and provide human-readable
    explanations of what the code does.
    
    Example:
        skill = CodeExplanationSkill()
        context = SkillContext(
            task_id="task_123",
            input_data={
                "code": "def factorial(n): return 1 if n <= 1 else n * factorial(n-1)",
                "detail_level": "detailed",
            }
        )
        result = await skill.run(context)
    """
    
    name = "code_explanation"
    description = "Explain code functionality in natural language"
    category = SkillCategory.CODING
    required_tools = ["file_read"]
    required_permissions = {"read_files", "llm_access"}
    version = "1.0.0"
    
    DETAIL_LEVELS = ["brief", "standard", "detailed"]
    
    def validate_input(self, input_data: Dict[str, Any]) -> bool:
        """Validate input data."""
        if "code" not in input_data:
            return False
        if not input_data.get("code", "").strip():
            return False
        detail_level = input_data.get("detail_level", "standard")
        if detail_level not in self.DETAIL_LEVELS:
            return False
        return True
    
    async def execute(self, context: SkillContext) -> SkillResult:
        """Execute code explanation.
        
        Args:
            context: Execution context with code to explain
            
        Returns:
            SkillResult with explanation
        """
        input_data = context.input_data
        code = input_data.get("code", "")
        detail_level = input_data.get("detail_level", "standard")
        language = input_data.get("language", "unknown")
        
        # Analyze code structure
        analysis = self._analyze_code_structure(code)
        
        # Generate explanation (placeholder for LLM)
        explanation = self._generate_explanation(code, detail_level, analysis)
        
        return SkillResult(
            skill_name=self.name,
            status=SkillStatus.COMPLETED,
            output={
                "summary": explanation.summary,
                "detailed_explanation": explanation.detailed_explanation,
                "complexity": explanation.complexity,
                "potential_issues": explanation.potential_issues,
                "suggestions": explanation.suggestions,
            },
            tokens_used=0,
        )
    
    def _analyze_code_structure(self, code: str) -> Dict[str, Any]:
        """Analyze basic code structure."""
        lines = code.split("\n")
        return {
            "line_count": len(lines),
            "has_functions": "def " in code or "function " in code,
            "has_classes": "class " in code,
            "has_loops": any(kw in code for kw in ["for ", "while ", "loop"]),
            "has_conditionals": "if " in code,
        }
    
    def _generate_explanation(
        self,
        code: str,
        detail_level: str,
        analysis: Dict[str, Any],
    ) -> ExplanationOutput:
        """Generate code explanation (placeholder for LLM)."""
        # Determine complexity
        complexity = "low"
        if analysis["line_count"] > 50 or analysis["has_classes"]:
            complexity = "high"
        elif analysis["line_count"] > 20 or analysis["has_loops"]:
            complexity = "medium"
        
        summary = f"Code with {analysis['line_count']} lines"
        if analysis["has_functions"]:
            summary += ", contains functions"
        if analysis["has_classes"]:
            summary += ", contains classes"
        
        return ExplanationOutput(
            summary=summary,
            detailed_explanation="Detailed explanation will be generated by LLM.",
            complexity=complexity,
            potential_issues=[],
            suggestions=[],
        )
